# This is a config for E2B sandbox template.
# You can use template ID (995vji2itp1cvdtnutvq) or template name (clarna-nextjs-test2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("clarna-nextjs-test2") # Sync sandbox
# sandbox = await AsyncSandbox.create("clarna-nextjs-test2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('clarna-nextjs-test2')

team_id = "d1e084f1-7eb1-4c6f-9b28-1cba0156e74d"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "clarna-nextjs-test2"
template_id = "995vji2itp1cvdtnutvq"
